apiVersion: apps/v1
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
{{- if eq .Values.installation_method "deployment" }}
kind: Deployment
spec:
  replicas: 1
{{- else }}
kind: DaemonSet
spec:
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name | quote }}
    spec:
      hostNetwork: {{ if eq .Values.ingress.method "hostnet" }}true{{else}}false{{end}}
      containers:
        - name: {{ .Release.Name | quote }}
          {{- with .Values.resources }}
          resources:
            {{- with .requests }}
            requests:
              {{- with .cpu }}
              cpu: {{ . | quote}}
              {{- end }}
              {{- with .memory }}
              memory: {{ . | quote}}
              {{- end }}
            {{- else }}
            requests: {}
            {{- end}}
            {{- with .limits }}
            limits:
              {{- with .cpu }}
              cpu: {{ . | quote}}
              {{- end }}
              {{- with .memory }}
              memory: {{ . | quote}}
              {{- end }}
            {{- else }}
            limits: {}
            {{- end}}
          {{- end }}
          image: {{ with .Values.image }}{{ . | quote }}{{ else }}ghcr.io/dns4acme/dns4acme:{{ .Chart.AppVersion }}{{ end }}
          {{- with .Values.listen_port }}{{ if lt (int .) 1025 }}
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
          {{- end }}{{ end }}
          env:
            - name: DNS4ACME_LISTEN
              value: "
                {{- if ne .Values.ingress_method "hostnet" -}}
                  0.0.0.0
                {{- else -}}
                  {{- with .Values.listen_ip -}}
                    {{- . -}}
                  {{- else -}}
                    0.0.0.0
                  {{- end -}}
                {{- end -}}:{{- with .Values.listen_port -}}
                  {{- . -}}
                {{- else -}}
                  5353
                {{- end -}}"
            - name: DNS4ACME_BACKEND
              value: {{ .Values.backend.type | quote }}
            - name: DNS4ACME_NAMESERVERS
              value: {{ .Values.nameservers | join "," | quote }}
            {{- with .Values.log_level }}
            - name: DNS4ACME_LOG_LEVEL
              value: {{ . | quote}}
            {{- end }}
            {{- if eq .Values.backend.type "kubernetes" }}
            - name: DNS4ACME_KUBERNETES_BEARER_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: DNS4ACME_KUBERNETES_CACERT_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: DNS4ACME_KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DNS4ACME_KUBERNETES_HOST
              value: kubernetes.default.svc
            {{- end }}
          ports:
            - containerPort: {{ with .Values.listen_port }}{{ . }}{{ else }}5353{{ end }}
              protocol: UDP
            - containerPort: {{ with .Values.listen_port }}{{ . }}{{ else }}5353{{ end }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ with .Values.listen_port }}{{ . }}{{ else }}5353{{ end }}
